-- 업체에대한 기본정보 및 img경로
CREATE TABLE EAT_IT_MUTUALLIST(
MUTUAL NVARCHAR2(30),
DIAL VARCHAR2(13),
ADDRESS NVARCHAR2(50),
KINDS VARCHAR2(20),
INTRODUCE NVARCHAR2(300),
CONSTRAINT MUTUAL_PK PRIMARY KEY(MUTUAL)
);

-- 회원가입
CREATE TABLE EAT_IT_MEMBER(
ID VARCHAR2(20),
PW VARCHAR2(20) NOT NULL,
NICK VARCHAR2(20) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
PHONENUMBER VARCHAR2(20) NOT NULL,
D DATE DEFAULT SYSDATE NOT NULL,
ADMIN CHAR(1) DEFAULT 0,
CONSTRAINT MEMBER_ID_PK PRIMARY KEY(ID)
);

-- 회원별 해당 업체 리뷰
CREATE TABLE EAT_IT_REVIEW(
MUTUAL NVARCHAR2(30),
ID VARCHAR2(20),
REVIEW NVARCHAR2(500),
review_id number(38),
D DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT REVIEW_FK FOREIGN KEY(MUTUAL) REFERENCES EAT_IT_MUTUALLIST(MUTUAL),
CONSTRAINT REVIEW_FK2 FOREIGN KEY(ID) REFERENCES EAT_IT_MEMBER(ID)
);

-- 지도좌표
CREATE TABLE EAT_IT_MAP(
MUTUAL NVARCHAR2(30),
GEOX NUMBER,
GEOY NUMBER,
CONSTRAINT MAP_FK FOREIGN KEY(MUTUAL) REFERENCES EAT_IT_MUTUALLIST(MUTUAL)
);

-- 상호별 이미지
CREATE TABLE EAT_IT_MUTUALIMG(
MUTUAL NVARCHAR2(30),
FIRSTIMG VARCHAR2(300),
SECONDIMG VARCHAR2(300),
THIRDIMG VARCHAR2(300),
FOURTHIMG VARCHAR2(300),
FIFTHIMG VARCHAR2(300),
CONSTRAINT IMG_FK FOREIGN KEY(MUTUAL) REFERENCES EAT_IT_MUTUALLIST(MUTUAL)
);

--찜목록
CREATE TABLE EAT_IT_LIKE(
ID VARCHAR2(20),
MUTUAL NVARCHAR2(30),
CONSTRAINT LIKE_FK FOREIGN KEY(ID) REFERENCES EAT_IT_MEMBER(ID),
CONSTRAINT LIKE_FK2 FOREIGN KEY(MUTUAL) REFERENCES EAT_IT_MUTUALLIST(MUTUAL)
);

COMMIT;
-- 여기까지 스크립트할 것







--테이블 삭제
DROP TABLE EAT_IT_MUTUALLIST CASCADE CONSTRAINTS;
DROP TABLE EAT_IT_REVIEW CASCADE CONSTRAINTS;
DROP TABLE EAT_IT_MEMBER CASCADE CONSTRAINTS;
DROP TABLE EAT_IT_MAP CASCADE CONSTRAINTS;
DROP TABLE EAT_IT_LIKE CASCADE CONSTRAINTS;
DROP TABLE EAT_IT_MUTUALIMG CASCADE CONSTRAINTS;


-- 조회
SELECT * FROM EAT_IT_MEMBER;
SELECT * FROM EAT_IT_MUTUALLIST;
SELECT * FROM EAT_IT_MUTUALIMG;
SELECT * FROM EAT_IT_REVIEW;
SELECT * FROM EAT_IT_MAP;
SELECT * FROM EAT_IT_LIKE;

COMMIT;